AWSTemplateFormatVersion: '2010-09-09'
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a0c8eebcdd6dcbd0 # ImageID valid only in us-east-1 region
      InstanceType: t4g.small
      KeyName: kpus1 # <-- Change to use your key-pair name
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo "Update the package list"
          apt update -y 
          echo "Upgrade"
          apt upgrade -y
          echo "Install the Apache web server"
          apt install -y apache2 
          echo "Display available UFW application profiles"
          ufw app list
          echo "Allow incoming traffic for Apache in UFW (Uncomplicated Firewall)"
          ufw allow in "Apache"
          ufw allow ssh
          echo "Enable UFW"
          ufw enable
          echo "Install MySQL server"
          apt install -y mysql-server


  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [webapp-security-group, dev]]
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
